try again

diff --git a/.github/workflows/node.js.yml b/.github/workflows/node.js.yml
--- a/.github/workflows/node.js.yml
+++ b/.github/workflows/node.js.yml
@@ -1,6 +1,3 @@
-# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
-# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs
-
 name: Node.js CI
 
 on:
@@ -11,29 +8,33 @@ on:
 
 jobs:
   build:
-
     runs-on: ubuntu-latest
 
     strategy:
       matrix:
         node-version: [20.18.0]
-        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
 
     steps:
-    # check out repository
+    # 检出代码
     - uses: actions/checkout@v4
 
-    - name: Change Directory to Homelette
-      run: cd Homelette
-
-    # set up node.js
+    # 设置 Node.js
     - name: Use Node.js ${{ matrix.node-version }}
       uses: actions/setup-node@v4
       with:
         node-version: ${{ matrix.node-version }}
         cache: 'npm'
 
-    # install dependencies
-    - name: Install Dependencies
+    # 安装依赖
+    - name: Install dependencies
       run: npm install
+      working-directory: ./Homelette
+
+    # 测试 Expo 启动
+    - name: Test Expo start
+      run: |
+        cd ./Homelette
+        npx expo start --no-dev --no-open &
+        sleep 15 # 给服务器一些时间来启动
+        curl --fail http://localhost:8081 || (echo "Expo failed to start" && exit 1)
       working-directory: ./Homelette
